### ISSUE TITLE
gitbook build error

### ISSUE THREAD

**Issue by reustonium** [FOSSRIT/HowToFOSS#58]
I installed gitbook via npm as described in your readme but when I run `gitbook build` locally I get the following error.

![error](https://i.imgur.com/OBEWSPH.png)

OS: Windows 8

**Comment by reustonium** [comment]
uninstalling `gitbook` and installing `gitbook-cli` fixed the issue for me, if you can confirm perhaps you might want to update the readme. Thanks!

**Comment by ryansb** [comment]
That seems right; go ahead and file a PR to fix the README.
